services:
  tower-defense:
    build: .
    ports:
      - "5173:5173" # Frontend
      - "8080:8080" # Faucet
      - "8081:8081" # GraphQL service
      - "9001:9001" # Shard proxy
      - "13001:13001" # Shard
    volumes:
      - .:/build
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info
